### ISSUE TITLE
Opening previews in Chrome window

### ISSUE THREAD

**Issue by stofte** [dbankier/vscode-instant-markdown#10]
Hello,

With a recent upgrade, Instant Markdown will often open MD files in Chrome, instead of inside VS Code. The URL being opened is http://localhost:8090/

If I click back and forth between some other file (a *.js in this case), the tab will randomly open and close in the browser. Occassionally opening two tabs? Opening VS Code after it was closed while open on an MD also gives alot of the same behavior. I don't have any other extensions than Instant Markdown installed.

I've observed this behavior across 2-3 Windows 10 x64 virtual machines where I use VSCode regularly. VSCode is 1.9.1, and I've removed the 3 other extensions I had installed, just in case.

I googled a comment about rewrites for Windows ;)

**Comment by dbankier** [comment]
Hi that is the module. If you want to just open in VS code you don't need this extension.
