### ISSUE TITLE
The browser showed 'not found'

### ISSUE THREAD

**Issue by TeaEra** [dbankier/vscode-instant-markdown#13]
Hi, @dbankier 

I updated the plugin but now when I opened 'localhost:8090', it showed 'not found'. Could you give me some instructions about this?

The version is 'vscode-instant-markdown@1.0.0' and I'm working with Windows VSCode.

**Comment by dpelkmann** [comment]
I'm working with VSCode on Linux and i got the same error message (v1.4.4). With version 1.3.0 the open browser function works - Bug in v1.4.4?

**Comment by dbankier** [comment]
@dpelkmann, I'm not using linux so I might need your help debugging this one.
