### ISSUE TITLE
[Bug] Previews lacks check lists support

### ISSUE THREAD

**Issue by Luchillo** [dbankier/vscode-instant-markdown#2]
So i'm using markdown to create check lists, which expects something like this:

``` md
- [x] App shell (is the home page)
- [ ] Angular Universal?
- [x] Lazy loading modules (probably needs SystemJS)
  - [x] Webpack code splitting?
  - [x] Angular 2 Router lazy loading?
- [ ] Offline: Service Worker with precache
- [x] Webpack dev server
- [x] HRM (Hot Module Replacement)
- [ ] Installable (Web app manifest)
- [ ] Testing
- [ ] Static template compilation (wait until Ng2 rc3 release)
```

The output directly from github is: 
![image](https://cloud.githubusercontent.com/assets/9698639/16304561/9115a842-391b-11e6-8610-a001614dd441.png)
But the actual output of your plugin which opens a new tab in browser is:
![image](https://cloud.githubusercontent.com/assets/9698639/16304578/ab3571d0-391b-11e6-9f4a-7a67cf867744.png)

**Comment by dbankier** [comment]
new release closes this

**Comment by Luchillo** [comment]
@dbankier Great, thanks.
