### ISSUE TITLE
Feature request: option to require keyboard shortcut to open preview

### ISSUE THREAD

**Issue by technivore** [dbankier/vscode-instant-markdown#20]
Hello, this extension is terrific but it can be kind of annoying when I open a md file just to make a quick edit, and suddenly my browser opens with a new tab. I don't necessarily want to disable the extension entirely for the workspace, but I also don't want it to always open a new browser tab whenever I switch to the md file in vs code. So I would like an option where the preview window doesn't open automatically but I could specify a key chord (like ctrl-shift-p or something) that would open it. Thank you!

**Comment by dbankier** [comment]
I hear. Will do.

**Comment by technivore** [comment]
Thank you!
