### ISSUE TITLE
Fix 'Repository' link in marketplace

### ISSUE THREAD

**Issue by JulioC** [dbankier/vscode-instant-markdown#24]
The Repository link in the [marketplace entry](https://marketplace.visualstudio.com/items?itemName=dbankier.vscode-instant-markdown) for this project points to a missing page: https://github.com/ziyasal/vscode-instant-markdown

**Comment by ziyasal** [comment]
Hi @dbankier 👍  for your work. I received emails about this issue so it'd be good to have look, thanks.

**Comment by alallier** [comment]
Yes this definitely needs looking in to. For the VS Code extension page this makes the extension look unsupported/deprecated
