### ISSUE TITLE
[request] Superscript (<sup>) Support

### ISSUE THREAD

**Issue by SamSlate** [dbankier/vscode-instant-markdown#25]
common syntax being `^`, looking something like:

`1^st, 2^nd, 3^rd`

result:

<p>1<sup>st</sup>, 2<sup>nd</sup>, 3<sup>rd</sup></p>

(html)

`<p>1<sup>st</sup>, 2<sup>nd</sup>, 3<sup>rd</sup></p>`

**Comment by dbankier** [comment]
done
