### ISSUE TITLE
Chrome Browser shows a blank window on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by nottoseethesun** [dbankier/vscode-instant-markdown#26]
This works perfectly for me on my Mac (Safari as default browser) but on Ubuntu, where I have Chrome set as my default browser, I just get a blank page with nothing in the web browser location bar (no `http://...` or `file:///...`.

Chrome and Ubuntu and VS Code are all up to date.  The in-VS Code side-by-side preview works great; just the browser view does not.

What can I do to troubleshoot this?

**Comment by dbankier** [comment]
The browser should be opening up to localhost:8090. 

I don't have an environment I can test it on,  but [this](https://github.com/dbankier/vscode-instant-markdown/blob/master/out/src/extension.js#L22) is the line of code that does that.

**Comment by nottoseethesun** [comment]
Thanks - yes I think it is a problem unrelated to this package, and related to opening links on Ubuntu from non-web-browsers/filesytems in general; xChat IRC has the same issue.  The command `xdg-open` works from the terminal to open links, but there is some issue with apps opening links.
