### ISSUE TITLE
`instantmarkdown.autoOpenBrowser` is not found and does not work.

### ISSUE THREAD

**Issue by rhys-vdw** [dbankier/vscode-instant-markdown#27]
![image](https://user-images.githubusercontent.com/822105/27673044-ef10a876-5ce1-11e7-8add-996b46226001.png)

Hey, I love the plugin but I only ever want to render pages in an editor split (instead of in my browser, which is always in a different workspace). Any idea why this isn't working?

**Comment by dbankier** [comment]
If you are only using it in the split, that is built into vscode so you don't need this module.

**Comment by rhys-vdw** [comment]
Oh... Ha ha. I thought it was from this plugin. Thanks!
