### ISSUE TITLE
Info Message to open browser is extremely annoying

### ISSUE THREAD

**Issue by gingters** [dbankier/vscode-instant-markdown#3]
Whenever I switch between markdown documents, I get the info message `"Open your browser to http://localhost:8090"`.

I can't turn it off.
This is extremely distracting and annoying.
I do know that I have the browser open, and I don't need a reminder whenever I switch to another markdown file in my folder.

There needs to be an option to turn this message off.
It is the most annoying extension I ever had. Having that message pop up ever single time and having to manually close the popup every single time is just a no-go.

Without being able to disable this message, I cannot use instant markdown any longer.

**Comment by dbankier** [comment]
Understood. Will fix it tomorrow.  Was added  as many windows users weren't
getting it...
