### ISSUE TITLE
Support header links

### ISSUE THREAD

**Issue by alallier** [dbankier/vscode-instant-markdown#30]
Support header based URL links, like GitHub, GitLab, and VSCode markdown preview support.

This is nice for testing table of contents and links to specific parts of the README

## GitHub
![githubheadersupport](https://user-images.githubusercontent.com/13004518/28463413-47102110-6dee-11e7-90bc-804e65fd841a.gif)

## VSCode
![vscodeheadersupport](https://user-images.githubusercontent.com/13004518/28463419-534c908a-6dee-11e7-9355-a52e5a2dd749.gif)

**Comment by alallier** [comment]
Seems like this is the relevant issue on `markdown-it`'s side https://github.com/markdown-it/markdown-it/issues/28

**Comment by alallier** [comment]
Seems there are some plugins written to support me idea...

https://github.com/leff/markdown-it-named-headers
https://github.com/adam-p/markdown-it-headinganchor
https://github.com/medfreeman/markdown-it-toc-and-anchor

Willing to work on a PR for this if you will support this ability

**Comment by dbankier** [comment]
@alalier, would be great to have a PR. The screenshots however are of vscode's in built markdown viewer. This plugin is used to open the preview (running on a different code base) in a browser.

**Comment by alallier** [comment]
Right yep I know was just showing that both VSCode and GitHub support this behavior. Will work on a PR soon!

**Comment by dbankier** [comment]
Thanks. Sorry I jumped in. I have people that have confused this plugin with the vscode feature.

**Comment by alallier** [comment]
Yep no problem always good to clarify. Love the extention and what to add on. Should have it up soon hopefully.
