### ISSUE TITLE
'instantmarkdown.openBrowser'

### ISSUE THREAD

**Issue by rfossella** [dbankier/vscode-instant-markdown#31]
Hi,

I successfully installed the extension within VSCode but when I try to execute I get the message:
**command 'instantmarkdown.openBrowser' not found** 

I uninstalled and tried to install manually (in Windows) but continue to get the same message.

Settings:  "instantmarkdown.autoOpenBrowser": true

Is there some other config option I need to set up?

Thanks!
Rob

**Comment by calzakk** [comment]
This is an old issue, so can be closed now.

You can't execute 'instantmarkdown.openBrowser' directly, you have to use "Instant Markdown: Open Browser" from the command palette (F1 or Ctrl+Shift+P).
