### ISSUE TITLE
Feature request: Add option to prevent the preview window from closing

### ISSUE THREAD

**Issue by calzakk** [dbankier/vscode-instant-markdown#40]
When switching to a non-markdown file, the preview window automatically closes. When frequently switching between markdown and non-markdown files, the preview window will open and close, and this can get really annoying! And it's even worse if the browser has no other open tabs ;)

Instead of closing straight away, maybe the preview can stay open as long as Code is still open? (It can always be manually closed, of course.)

**Comment by dbankier** [comment]
Makes sense. Would be a pretty quick fix. PR?

**Comment by calzakk** [comment]
Thanks for this David, much appreciated!

I'm seeing an issue though: when switching to a non-markdown file with autoCloseServerAndBrowser disabled, the browser indeed stays open, but going back to the markdown file and editing it doesn't cause the changes to appear in the browser.

Closing the browser doesn't help, I have to close and reopen Code for the browser preview to start working again. This happens on both Windows and Linux.

**Comment by dbankier** [comment]
Yep sorry. Just fixed it. Pushing out new version 1.4.1 now.

**Comment by calzakk** [comment]
Looks like it's working nicely now, thanks very much :)
