### ISSUE TITLE
Opening browser for wrong file type

### ISSUE THREAD

**Issue by hbennet** [dbankier/vscode-instant-markdown#43]
I was working with PowerShell files in VS Code and Instant Markdown was parsing the files as if they contained markdown code and was opening the browser for each file. I believe it was also doing this for SQL script files that included a lot of comments using the "--" syntax, but I was unable to reliably repeat this behavior.

**Comment by dbankier** [comment]
Sound like a vscode issue. The plugin is triggered by vscode.
