### ISSUE TITLE
Hope it support mermaid, yuml or plantuml.

### ISSUE THREAD

**Issue by ed0522** [dbankier/vscode-instant-markdown#52]

**Comment by dbankier** [comment]
Sure. Happy for pull requests.

**Comment by ed0522** [comment]
I am a business analyst and I need to draw many sophisticated and complex flowchart. I've already tried Powerpoint, Edraw (and other GUI diagram tools), plantuml. At last, I found the best solution is vs code + markdown + mermaid, and preview with your instant markdown extension. 
But now your extension doesn't support mermaid, if you have no plan on it, I want to do this job although I don't have relevent experience. I will learn it.
If I encounter with some problems, I hope you can give me a hand.
Thanks!

**Comment by ed0522** [comment]
Also, there is another solution instead of adding mermaid or plantuml to instant markdown, that we can find a way to open the vs code preview tab in a new window which can be maximized to full screen.
Maybe this one is easier. I don't know the detail, but maybe it's a possible direction.

**Comment by AjitDingankar** [comment]
I found a work-around to PlantUML rendering: a "bare" code block (without the code block markers of triple back-quotes \`\`\`) with `@startuml` and `@enduml` works in Instant Markdown. Of course that messes up the Markdown Preview Enhanced extension (which apparently doesn't know how to execute a plantuml code block although Mermaid and Graphviz code blocks run OK).

**Comment by AjitDingankar** [comment]
I'd really appreciate it if you develop Mermaid support! 

> I am a business analyst and I need to draw many sophisticated and complex flowchart. I've already tried Powerpoint, Edraw (and other GUI diagram tools), plantuml. At last, I found the best solution is vs code + markdown + mermaid, and preview with your instant markdown extension.
> But now your extension doesn't support mermaid, if you have no plan on it, I want to do this job although I don't have relevent experience. I will learn it.
> If I encounter with some problems, I hope you can give me a hand.
> Thanks!

**Comment by dbankier** [comment]
just added mermaid support. will be in next release
