### ISSUE TITLE
Opens for everything

### ISSUE THREAD

**Issue by Franatec** [dbankier/vscode-instant-markdown#56]
This only started happening in the last week or so. The server is starting up for every kind of file now. Does it look inside the code for markdown (I use markdown style format for comments occasionally)? Or does it rely on the extension?

**Comment by TonyApuzzo** [comment]
Glad to know I'm not the only one seeing this. I temporarily disabled auto open browser until this is fixed.

**settings.json**
```
  "instantmarkdown.autoOpenBrowser": false
```

**Comment by Franatec** [comment]
@TonyApuzzo, I forgot about that setting. That's certainly helpful, thanks!

**Comment by dbankier** [comment]
Tested on OSX and I can't replicate.

**Comment by Franatec** [comment]
My apologies, I should have included my OS in the initial comment. I'm on Windows 10.

**Comment by qRoC** [comment]
Same on macOS

**Comment by techrev** [comment]
> Tested on OSX and I can't replicate.

I'm seeing this same issue on OSX Mojave (10.14.6)
