### ISSUE TITLE
Under Win32, vscode-instant-markdown would cause High CPU usage.

### ISSUE THREAD

**Issue by lygstate** [dbankier/vscode-instant-markdown#6]

**Comment by agc93** [comment]
I'm also experiencing this problem.

On my machine, it manifests as an incredibly high number of `node.exe` processes being spawned (for `instant-markdown-d`) and terminating, so many that the CPU quickly maxes out. Generally, this lasts for between 15 and 20 seconds, and occurs every few minutes.

Also, and possibly relatedly, even after closing the VS Code window, there is one `node.exe` (again `instant-markdown-d`) process left running.

**Comment by dbankier** [comment]
the latest release is a complete rewrite should close this issue.
