### ISSUE TITLE
Plugin DOSd my system! 

### ISSUE THREAD

**Issue by leegee** [dbankier/vscode-instant-markdown#7]
- VSCode Version: Code - Insiders 1.9.0-insider (b2d2a79da81853bff6e1c60876c9cee8582f9e61, 2017-01-11T07:09:02.740Z)
- OS Version: Darwin x64 15.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.2|
|vscode-eslint|dbaeumer|1.2.2|
|vscode-instant-markdown|dbankier|0.2.1|
|docthis|joelday|0.3.9|
|vscode-exec-node|miramac|0.2.1|
|joinlines|webdokkeren|1.1.1|

---

I've been using the plug-in for many months, without a problem. 

Jut now I opened an .md file to edit, and noticed my machine's fan was spinning up — then noticed that there were many, many tabs open in Chrome, all coming from this plugin.

I shut VSCode, and pressed CTRL+W perhaps 100 times to close as many tabs.

Re-opened VSCode, re-opened the .md file, and then got two tabs opened by the plugin.

Closed the document and repeated with the same results.

Closed the document, re-opened and now get now tab.

Is there a log I could attach?

*NB* THis is the latest Insiders build of VSCode.

**Comment by dbankier** [comment]
Sorry about that!

This extensions is just a simple wrapper around https://github.com/suan/instant-markdown-d.
The extension code is really quite basic. If you step through it, all it does is try to send the contents of the markdown file to `instant-markdown-d` when it opens or the file is modified (the `update()` function). If it gets a connection error, it assumes that the services is not running and tries to `initialise()` it. When `instant-markdown-d` starts it opens a browser window (on osx). Based on this, either the insider build sending multiple events simultaneously or something is killing the server startup (it runs on `8080`).

Hope that helps.

**Comment by leegee** [comment]
Has the issue now been fixed?

**Comment by dbankier** [comment]
Yep. Should be.

**Comment by leegee** [comment]
Super, thanks.
