### ISSUE TITLE
Runs on port 8090

### ISSUE THREAD

**Issue by oscarvazquez** [dbankier/vscode-instant-markdown#9]
It looks like you're running the server on port 8090 but in your readme you have that it's running on 3000
```
        http.listen(8090, function(){
            console.log('listening on *:8090');
            options.started()
        });
```

**Comment by dbankier** [comment]
Correct. Do you want to update the README?

**Comment by dbankier** [comment]
closed by https://github.com/dbankier/vscode-instant-markdown/pull/11
